### ISSUE TITLE
Malformed date display

### ISSUE THREAD

**Issue by fischermario** [linuxdeepin/dde-control-center#8]
The date is not displayed correctly in the "date and time" section of the control center. The same applies to the lockscreen and to the calendar in the panel.

It seems that this problem only occurs if the system language is NOT set to Chinese or English.

Link to a discussion in the community forums: http://en.bbs.deepin.org/forum.php?mod=viewthread&tid=30516

![nodate2_20160101](https://cloud.githubusercontent.com/assets/10214295/12074193/0b3ad55a-b147-11e5-9d83-e974e9809dc4.png)
![nodate_20160101](https://cloud.githubusercontent.com/assets/10214295/12074192/0b399a64-b147-11e5-93a1-7e6bc1936c10.png)
![nodate3_20160102](https://cloud.githubusercontent.com/assets/10214295/12074243/0045395a-b148-11e5-8ddd-fe0afb690e0f.png)

**Comment by aggalex** [comment]
Confirmed in Greek too, but with letters of the Greek alphabet.

**Comment by sbwtw** [comment]
@fischermario hello, what language are u choosing? it seems translation file not correct

**Comment by fischermario** [comment]
@sbwtw Hello! My system language is German. But considering other people's comments, I guess German is not the only language that is affected by this bug. Right now at least Greek, French and Spanish are also confirmed.

**Comment by sbwtw** [comment]
sorry, this problem we have record. and i think it will be solve soon. 
thanks for report 😘


On 01/08/2016 06:44 PM, Mario Fischer wrote:
>
> @sbwtw <https://github.com/sbwtw> Hello! My system language is German. 
> But considering other people's comments, I guess German is not the 
> only language that is affected by this bug. Right now at least Greek, 
> French and Spanish are also confirmed.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/linuxdeepin/dde-control-center/issues/8#issuecomment-169960956>.
>

-- 
*石博文*

**Comment by aggalex** [comment]
So, I found that the malformed date in greek is "ηηηη, ηη ΜΜΜΜ εε". I guess "η" comes from "ημέρα", wich means day, "M" comes from "Μήνας", wich means month and "ε" comes from "έτος", wich means year. I also guess that where 2 letters are a number should have been there, and where 4 letters are a word should have been. Which means, that the variable taken from the translation file is wrong, which means that the code should be updated to support the translation file better. I'm not sure about the programming language, but I guess the day variable in german returns sometimes "CET" or "t", which "t" I think comes from the word "tag", wich means day. And the year variable in german returns "j" wich I also guess it's from the word "jahr" wich in German means year. Come on Deepin, I gave you some clues, I guess you will fix it right?

**Comment by hualet** [comment]
@aggalex Sure you are :smile:  The truth is that every languages get its own translation file, we officially translated English and Chinese, so they are OK. Translators from other countries may have confused by the source characters, so they get it all wrong. I'll find a way to fix it, Mr.Holmes :joy:

**Comment by aggalex** [comment]
If every translation has it's own file, then it's much better than I thought. I read somewhere you take translations through Transifex. I don't know anything about it, but if you add the xml translation code, and transifex adds the translations, then you should review the code you entered in Transifex. I'd like to help with the fix, so could I have a copy of the greek translation file and a copy of the english translation file? If I find any problem, I'll fix it and mark it with a comment (like `<!-- Here goes the explanation of the fix -->`), so that you can easily fix the problem and have a nice date view in my system.

Also, I have found that on classic view of the dock the time is also malformed. It shows ωω:λλ, in which I think "ω" comes from "ώρες", which mean "hour", and "λ" comes from "λεπτά" wich means "minutes"

**Comment by hualet** [comment]
@aggalex you don't wink too much! you just shares the same habit with @manateelazycat, he winks too much. :P

I'm not sure if you can format the date to a proper format since the source just contains "dddd", "MM", "dd", things likes will be used by the program to format the date, for example, "dddd" stands for "2016" this year. Check out this link to see if you can totally understand.

The translation file can be download from "https://www.transifex.com/linuxdeepin/deepin-desktop-environment/dde-control-center/el/download/for_translation/".

**Comment by aggalex** [comment]
Hey, I've found a strange area of the transtlation file, which has translation to "hh:mm" as "ωω:λλ" etc. I commented it all out using `<!-- -->` in the file I send to you. So, maybe the program sets the label of the time/date as the raw input of the translation, which is a bug. Could you please send me the function that defines the date (and maybe time), so that maybe I can do something with it? Also, please tell me the language you used to do this. (^‿- )

*PS:*
I had to rename the translation file to end with *.txt, so that I can upload it. You can of course rename it.

*The translation file:*
[for_translation_deepin-desktop-environment_dde-control-center_el.txt](https://github.com/linuxdeepin/dde-control-center/files/87529/for_translation_deepin-desktop-environment_dde-control-center_el.txt)

**Comment by hualet** [comment]
[datetime-fromatter.zip](https://github.com/linuxdeepin/dde-control-center/files/88487/datetime-fromatter.zip)

The source characters like "dddd" "MM" are used to format the datetime, some of them are transformed to localized string, some of them are transformed to numbers. I don't know how to explain it, so I wrote a  simple program that can help you to understand it. Use is like this:

./datetime-formatter FORMAT_STRING

for example, "./datetime-formatter dddd" gives "2015", "./datetiem-formatter dddd年" gives "2015年".

If your machine is 64-bit, then there's a binary already. You should build it yourself otherwise.

**Comment by aggalex** [comment]
I understand how it works, and testing it made me understand that one of my guesses was (paradoxly) right again. So, what you should do is remove the part that I commented from every translation file and recode everything to use the english characters, because in the transifex translation you added entries to translate the format of the datetime.

### To make you understand:
##### In my language:
- The right:

```
$ ./datetime-formatter dddd dd/MM/yyyy
" dddd dd/MM/yyyy" " Τετάρτη 13/01/2016"
```

"Τετάρτη" means "Wednesday"

- What do you do:

```
$ ./datetime-formatter ηηηη ηη/ΜΜ/εεεε
" ηηηη ηη/ΜΜ/εεεε" " ηηηη ηη/ΜΜ/εεεε"
```

Because this are the lines you have wrong in the translation file that affects datetime formatting:
```xml
<name>DateTimePlugin</name>
    <message>
        <location filename="../dock-plugins/dde-dock-datetime-plugin/datetimeplugin.cpp" line="137"/>
        <source>MMM dd</source>
        <translation>ΜΜΜ ηη</translation>
    </message>
    <message>
        <location filename="../dock-plugins/dde-dock-datetime-plugin/datetimeplugin.cpp" line="138"/>
        <source> hh:mm </source>
        <translation> ωω:λλ </translation>
    </message>
    <message>
        <location filename="../dock-plugins/dde-dock-datetime-plugin/datetimeplugin.cpp" line="138"/>
        <location filename="../dock-plugins/dde-dock-datetime-plugin/datetimeplugin.cpp" line="271"/>
        <source> hh:mm A</source>
        <translation> ωω:λλ ΠΜ</translation>
    </message>
    <message>
        <location filename="../dock-plugins/dde-dock-datetime-plugin/datetimeplugin.cpp" line="139"/>
        <source>ddd</source>
        <translation>ηηη</translation>
    </message>
    <message>
        <location filename="../dock-plugins/dde-dock-datetime-plugin/datetimeplugin.cpp" line="140"/>
        <source>ddd MMM dd</source>
        <translation>ηηη ΜΜΜ ηη</translation>
    </message>
```

So, do you get what you should do?

I could help doing it on some translation files if I was granted access to the transifex files and if I could find some time in my full schedule.

**Comment by sbwtw** [comment]
is correct in last version ? @aggalex

**Comment by aggalex** [comment]
Sorry, but there is a problem right now... I tried installing Android and mixed gpt with mbr and now I can't boot... But I'll review the xml file anyway in my Lubuntu live...

**Comment by aggalex** [comment]
Becareful of the lines 1757-1762 in the translatition file. This:
`
    <message>
        <location filename="../modules/datetime/timewidget.cpp" line="111"/>
        <location filename="../dock-plugins/dde-dock-datetime-plugin/datetimeplugin.cpp" line="252"/>
        <source>dddd, dd MMMM yyyy</source>
        <translation>yyyy-MM-dd dddd</translation>
    </message>
`
Should not have been here too. If you can't find any wrong translations in the file other than these, then push the updates!

**Comment by aggalex** [comment]
I updated my PC and it got fixed! Thank you for all your time! [and for listening to my suggestions :-P ]

Please mark this as done.

**Comment by fischermario** [comment]
It is not done. The date display on the lockscreen is still wrong.

**Comment by hualet** [comment]
I've let our translator correct all the errors, and there'll be an update this weekend, let's see if the that'll solve all the problems.

**Comment by aggalex** [comment]
Oh, I didn't see that.

**Comment by hualet** [comment]
@aggalex There will. :smiley:
