### ISSUE TITLE
Monitor enable/disable feature 

### ISSUE THREAD

**Issue by nayanajith** [linuxdeepin/dde-control-center#98]
Please add monitor enable/disable feature

**Comment by darthcabs** [comment]
+1
This feature would be incredibly useful when you want to work connected to a monitor, with the laptop lid closed. If the laptop screen is enabled, even though the lid is closed, then some apps when opened will go straight to there, making it impossible to bring them back without opening the lid and dragging the apps to the external monitor.

Otherwise thank you very much for this amazing disto! Increadibly reliable, stable and good looking!

**Comment by jouyouyun** [comment]
@hualet

**Comment by hualet** [comment]
@nayanajith you can use super+p to switch to a single monitor enabled mode.

**Comment by hualet** [comment]
@darthcabs you can just close your lid when your computer's connected a an external monitor, it will automatically shutdown your built-in monitor and use the external one.
